version: "3.8"

services:
  server:
    container_name: fastapi_server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:8000" # Map port 80 on the host to port 8000 on the container
    volumes:
      - .:/usr/src/app # Mount the current directory to the container
    environment:
      - MONGO_URL=mongodb://db:27017/ml_website1 # MongoDB connection URL
    depends_on:
      - db # Ensure that the FastAPI app waits for the MongoDB service
    networks:
      - network

  db:
    image: mongo:latest # Use the official MongoDB image
    environment:
      MONGO_INITDB_DATABASE: ml_website1 # Name of the database to create
    volumes:
      - mongo_data:/data/db # Persist MongoDB data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  mongo_data: # Named volume to persist MongoDB data
